<!doctype html>
<html lang="{{ dv('current_language',get_defined_vars()) }}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#10100f">
<title>{{ dv('seo.title',get_defined_vars()) }}</title><meta name="description" content="{{ dv('seo.description',get_defined_vars()) }}"><meta name="robots" content="{{ dv('seo.robots',get_defined_vars()) }}"><link rel="canonical" href="{{ dv('seo.canonical',get_defined_vars()) }}">
@forelse((dv('seo.alternates',get_defined_vars())??[]) as $alt)<link rel="alternate" hreflang="{{ dv('alt.language',get_defined_vars()) }}" href="{{ dv('alt.url',get_defined_vars()) }}">@empty @endforelse<link rel="alternate" hreflang="x-default" href="{{ dv('seo.default_url',get_defined_vars()) }}">
<meta property="og:title" content="{{ dv('seo.og_title',get_defined_vars()) }}"><meta property="og:description" content="{{ dv('seo.og_description',get_defined_vars()) }}"><meta property="og:type" content="{{ dv('seo.og_type',get_defined_vars()) }}"><meta property="og:url" content="{{ dv('seo.og_url',get_defined_vars()) }}"><meta property="og:site_name" content="{{ dv('seo.og_site_name',get_defined_vars()) }}"><?php if(truth(dv('seo.og_image',get_defined_vars()))): ?><meta property="og:image" content="{{ dv('seo.og_image',get_defined_vars()) }}"><?php endif; ?><?php if(truth(dv('seo.og_video',get_defined_vars()))): ?><meta property="og:video" content="{{ dv('seo.og_video',get_defined_vars()) }}"><?php endif; ?><meta property="og:locale" content="<?php if((dv('current_language',get_defined_vars()) == 'ru')): ?>ru_RU<?php elseif((dv('current_language',get_defined_vars()) == 'kk')): ?>kk_KZ<?php else: ?>en_US<?php endif; ?>">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{{ dv('seo.og_title',get_defined_vars()) }}"><meta name="twitter:description" content="{{ dv('seo.og_description',get_defined_vars()) }}"><meta name="twitter:image" content="{{ dv('seo.og_image',get_defined_vars()) }}">
<?php if(truth(dv('site.google_verification',get_defined_vars()))): ?><meta name="google-site-verification" content="{{ dv('site.google_verification',get_defined_vars()) }}"><?php endif; ?><?php if(truth(dv('site.yandex_verification',get_defined_vars()))): ?><meta name="yandex-verification" content="{{ dv('site.yandex_verification',get_defined_vars()) }}"><?php endif; ?>
@section('preload')<?php echo $__env->yieldSection(); ?><link rel="icon" href="<?php if(truth(dv('site.favicon',get_defined_vars()))): ?>{{ dv('site.favicon.url',get_defined_vars()) }}<?php else: ?>{{ '/static/'.'img/favicon-original.jpg' }}<?php endif; ?>" >@section('font_preloads')<link rel="preload" href="{{ build_asset('static/fonts/montserrat-site.woff2') }}" as="font" type="font/woff2" crossorigin><link rel="preload" href="{{ build_asset('static/fonts/golos-night.woff2') }}" as="font" type="font/woff2" crossorigin><?php echo $__env->yieldSection(); ?>

<?php $styles=critical_css('frontend/main.js');  ?><style nonce="{{ dv('request.csp_nonce',get_defined_vars()) }}">{{ dv('styles',get_defined_vars()) }}</style>
@section('extra_head')<?php echo $__env->yieldSection(); ?>
@forelse((dv('schemas',get_defined_vars())??[]) as $schema)<script type="application/ld+json" nonce="{{ dv('request.csp_nonce',get_defined_vars()) }}">{{ df(dv('schema',get_defined_vars()),'json_ld') }}</script>@empty @endforelse
<script nonce="{{ dv('request.csp_nonce',get_defined_vars()) }}">document.documentElement.classList.add('js')</script><script type="module" src="{{ build_asset('frontend/main.js') }}" defer></script></head>
<body class="@section('body_class')<?php echo $__env->yieldSection(); ?>"><a class="skip-link" href="#main">{{ site_text('Перейти к содержимому') }}</a>
{{ icon_sprite() }}<div class="header-scroll-marker" aria-hidden="true"></div><header class="site-header"><div class="header-inner"><a class="brand" data-city-home href="{{ home_url() }}" aria-label="LEGIONAUTORENT — {{ site_text('Главная') }}"><img src="<?php if(truth(dv('site.logo',get_defined_vars()))): ?>{{ dv('site.logo.url',get_defined_vars()) }}<?php else: ?>{{ '/static/'.'img/logo-site.webp' }}<?php endif; ?>" width="164" height="42" alt="LEGIONAUTORENT"></a>
<details class="city-menu"><summary><span class="location-dot" aria-hidden="true"></span><span data-empty-label="{{ site_text('Выберите город') }}" data-city-label><?php if(truth(dv('request.selected_city',get_defined_vars()))): ?>{{ df(dv('request.selected_city',get_defined_vars()),'tr','name') }}<?php else: ?>{{ site_text('Выберите город') }}<?php endif; ?></span>{{ icon('chevron') }}</summary><ul>@forelse((dv('nav_cities',get_defined_vars())??[]) as $nav_city)<li><a data-city-switch="{{ $nav_city->slug }}" href="{{ city_switch_url($nav_city) }}">{{ df(dv('nav_city',get_defined_vars()),'tr','name') }}</a></li>@empty @endforelse</ul></details>
<nav class="desktop-nav" aria-label="{{ site_text('Главное меню') }}">@forelse((dv('request.main_menu',get_defined_vars())??[]) as $link)<a data-site-nav href="{{ menu_url(dv('link.path',get_defined_vars())) }}">{{ dv('link.display_label',get_defined_vars()) }}</a>@empty @endforelse</nav>
<div class="language-switch" aria-label="{{ site_text('Язык') }}">@forelse((dv('language_links',get_defined_vars())??[]) as $item)<a href="{{ dv('item.url',get_defined_vars()) }}" lang="{{ dv('item.language',get_defined_vars()) }}" <?php if((dv('item.language',get_defined_vars()) == dv('current_language',get_defined_vars()))): ?>aria-current="true"<?php endif; ?>>{{ dv('item.label',get_defined_vars()) }}</a>@empty @endforelse</div>
<a class="header-phone" href="tel:{{ df(dv('site.phone',get_defined_vars()),'phone_link') }}" data-event="click_phone">{{ dv('site.phone',get_defined_vars()) }}</a>
<details class="mobile-menu"><summary aria-label="{{ site_text('Открыть меню') }}"><span></span><span></span></summary><nav aria-label="{{ site_text('Мобильное меню') }}">@forelse((dv('request.mobile_menu',get_defined_vars())??[]) as $link)<a data-site-nav href="{{ menu_url(dv('link.path',get_defined_vars())) }}">{{ dv('link.display_label',get_defined_vars()) }}</a>@empty @endforelse<a href="tel:{{ df(dv('site.phone',get_defined_vars()),'phone_link') }}">{{ dv('site.phone',get_defined_vars()) }}</a><div class="language-switch" aria-label="{{ site_text('Язык') }}">@forelse((dv('language_links',get_defined_vars())??[]) as $item)<a href="{{ dv('item.url',get_defined_vars()) }}" lang="{{ dv('item.language',get_defined_vars()) }}" <?php if((dv('item.language',get_defined_vars()) == dv('current_language',get_defined_vars()))): ?>aria-current="true"<?php endif; ?>>{{ dv('item.label',get_defined_vars()) }}</a>@empty @endforelse</div></nav></details></div></header>
<main id="main" tabindex="-1">@section('content')<?php echo $__env->yieldSection(); ?></main>
<footer class="site-footer"><div class="container footer-top"><div><a class="brand" data-city-home href="{{ home_url() }}"><img src="<?php if(truth(dv('site.logo',get_defined_vars()))): ?>{{ dv('site.logo.url',get_defined_vars()) }}<?php else: ?>{{ '/static/'.'img/logo-site.webp' }}<?php endif; ?>" width="164" height="42" alt="LEGIONAUTORENT"></a><p>{{ df(dv('site',get_defined_vars()),'tr','footer_text') }}</p><a class="footer-phone" href="tel:{{ df(dv('site.phone',get_defined_vars()),'phone_link') }}" data-event="click_phone">{{ dv('site.phone',get_defined_vars()) }}</a></div><nav aria-label="{{ site_text('Города') }}"><p class="eyebrow">{{ site_text('Города') }}</p>@forelse((dv('nav_cities',get_defined_vars())??[]) as $nav_city)<a href="{{ df(dv('nav_city.legacy_path',get_defined_vars()),'local_url') }}?city={{ dv('nav_city.slug',get_defined_vars()) }}">{{ df(dv('nav_city',get_defined_vars()),'tr','name') }}</a>@empty @endforelse</nav><nav aria-label="{{ site_text('Информация') }}"><p class="eyebrow">{{ site_text('Информация') }}</p>@forelse((dv('footer_pages',get_defined_vars())??[]) as $page)<a href="{{ df(dv('page.path',get_defined_vars()),'local_url') }}">{{ df(dv('page',get_defined_vars()),'tr','title') }}</a>@empty @endforelse<a href="{{ df('/faq/','local_url') }}">FAQ</a></nav><div><p class="eyebrow">{{ site_text('Мы на связи') }}</p><a href="{{ dv('site.whatsapp_url',get_defined_vars()) }}" target="_blank" rel="noopener noreferrer" data-event="click_whatsapp">WhatsApp ↗</a><?php if(truth(dv('site.instagram',get_defined_vars()))): ?><a href="{{ dv('site.instagram',get_defined_vars()) }}" rel="noopener noreferrer" target="_blank">Instagram ↗</a><?php endif; ?><p>{{ df(dv('site',get_defined_vars()),'tr','address') }}</p></div></div><div class="container footer-bottom"><span>© {{ date('Y') }} LEGIONAUTORENT</span><a href="{{ df('/privacy/','local_url') }}">{{ site_text('Конфиденциальность') }}</a><span>{{ site_text('Разработано в') }} <a href="https://astanacreative.kz/" target="_blank" rel="noopener noreferrer">Astana Creative</a></span></div></footer>
<div class="mobile-contact"><a href="tel:{{ df(dv('site.phone',get_defined_vars()),'phone_link') }}" data-event="click_phone">{{ icon('phone') }}{{ site_text('Позвонить') }}</a><a class="mobile-wa" href="{{ dv('site.whatsapp_url',get_defined_vars()) }}" data-mobile-wa target="_blank" rel="noopener noreferrer" data-event="click_whatsapp">{{ icon('whatsapp') }}WhatsApp</a></div>
<?php if(truth(dv('analytics_enabled',get_defined_vars()))): ?>@include('components.analytics')<?php endif; ?>
</body></html>
