<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('django_admin_log', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->dateTime('action_time', 6);
            $t->unsignedBigInteger('user_id');
            $t->unsignedBigInteger('content_type_id')->nullable();
            $t->longText('object_id')->nullable();
            $t->string('object_repr', 200);
            $t->bigInteger('action_flag');
            $t->longText('change_message');
        });
        Schema::create('auth_permission', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->string('name', 255);
            $t->unsignedBigInteger('content_type_id');
            $t->string('codename', 100);
        });
        Schema::create('auth_group_permissions', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->unsignedBigInteger('group_id');
            $t->unsignedBigInteger('permission_id');
        });
        Schema::create('auth_group', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->string('name', 150)->unique();
        });
        Schema::create('auth_user_groups', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->unsignedBigInteger('user_id');
            $t->unsignedBigInteger('group_id');
        });
        Schema::create('auth_user_user_permissions', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->unsignedBigInteger('user_id');
            $t->unsignedBigInteger('permission_id');
        });
        Schema::create('auth_user', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->string('password', 128);
            $t->dateTime('last_login', 6)->nullable();
            $t->boolean('is_superuser')->default(false);
            $t->string('username', 150)->unique();
            $t->string('first_name', 150)->default('');
            $t->string('last_name', 150)->default('');
            $t->string('email', 254)->default('');
            $t->boolean('is_staff')->default(false);
            $t->boolean('is_active')->default(true);
            $t->dateTime('date_joined', 6);
            $t->rememberToken();
        });
        Schema::create('django_content_type', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->string('app_label', 100);
            $t->string('model', 100);
        });
        Schema::create('core_sitesettings', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->string('name', 100)->default('LEGIONAUTORENT');
            $t->string('phone', 40)->default('+7 (705) 727-77-77');
            $t->string('whatsapp', 20)->default('77057277777');
            $t->string('email', 254)->default('');
            $t->string('address', 250)->default('');
            $t->string('hours', 120)->default('');
            $t->string('logo', 100)->default('');
            $t->string('favicon', 100)->default('');
            $t->string('hero_image', 100)->default('');
            $t->string('hero_video_file', 100)->default('');
            $t->string('hero_mobile_video_file', 100)->default('');
            $t->string('hero_mobile_video_path', 250)->default('');
            $t->string('hero_mobile_image', 100)->default('');
            $t->string('hero_ending_image', 100)->default('');
            $t->bigInteger('hero_video_fps')->default('60');
            $t->string('hero_model', 100)->default('');
            $t->string('hero_model_license', 250)->default('');
            $t->string('hero_model_path', 250)->default('/static/models/hero.glb');
            $t->string('hero_poster_path', 250)->default('/static/hero/hero-poster-60fps-desktop.webp');
            $t->string('hero_mobile_poster_path', 250)->default('/static/hero/hero-poster-60fps-mobile.webp');
            $t->string('hero_ending_path', 250)->default('/static/hero/hero-ending-60fps.webp');
            $t->string('hero_video_path', 250)->default('/static/hero/hero-60fps.mp4');
            $t->json('hero_names');
            $t->boolean('enable_hero_3d')->default(true);
            $t->boolean('enable_hero_video')->default(true);
            $t->boolean('hero_placeholder')->default(true);
            $t->longText('robots_text');
            $t->string('default_seo_title', 250)->default('LEGIONAUTORENT — прокат автомобилей');
            $t->longText('default_seo_description');
            $t->longText('whatsapp_message');
            $t->boolean('notifications_enabled')->default(false);
            $t->string('hero_title', 200)->default('Без водителя. Под ваши планы.');
            $t->string('hero_price_caption', 150)->default('');
            $t->string('hero_steps_caption', 250)->default('');
            $t->longText('hero_text');
            $t->unsignedBigInteger('hero_car_id')->nullable();
            $t->string('instagram', 200)->default('');
            $t->string('map_url', 200)->default('');
            $t->string('footer_text', 250)->default('Автомобиль под ваши планы.');
            $t->string('gtm_id', 30)->default('');
            $t->string('ga4_id', 30)->default('');
            $t->string('metrika_id', 30)->default('');
            $t->string('google_verification', 150)->default('');
            $t->string('yandex_verification', 150)->default('');
            $t->boolean('show_partner_section')->default(true);
            $t->string('partner_title', 200)->default('Стать партнером LEGIONAUTORENT');
            $t->longText('partner_description');
            $t->string('partner_phone', 40)->default('');
            $t->string('partner_whatsapp', 20)->default('');
            $t->longText('partner_whatsapp_message');
        });
        Schema::create('core_contentblock', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->string('kind', 20);
            $t->string('title', 200);
            $t->longText('text');
            $t->boolean('active')->default(true);
            $t->bigInteger('sort_order')->default('0');
        });
        Schema::create('core_interfacetext', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->string('source', 500)->unique();
            $t->string('section', 150);
            $t->longText('ru');
            $t->longText('kk');
            $t->longText('en');
        });
        Schema::create('core_sitesection', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->string('key', 30)->unique();
            $t->boolean('active')->default(true);
            $t->bigInteger('sort_order')->default('0');
        });
        Schema::create('core_menulink', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->string('area', 20);
            $t->string('label', 80);
            $t->string('label_kk', 100)->default('');
            $t->string('label_en', 100)->default('');
            $t->string('path', 250);
            $t->boolean('active')->default(true);
            $t->bigInteger('sort_order')->default('0');
        });
        Schema::create('locations_city', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->string('seo_title', 250)->default('');
            $t->longText('seo_description');
            $t->string('seo_h1', 250)->default('');
            $t->string('canonical_url', 200)->default('');
            $t->string('robots', 40)->default('index,follow');
            $t->string('og_title', 250)->default('');
            $t->longText('og_description');
            $t->string('og_image', 200)->default('');
            $t->json('legacy_meta');
            $t->dateTime('created_at', 6);
            $t->dateTime('updated_at', 6);
            $t->string('name', 100);
            $t->string('name_in', 120)->default('');
            $t->string('slug', 50)->unique();
            $t->string('legacy_path', 250)->unique()->default('');
            $t->longText('description');
            $t->longText('hero_text');
            $t->string('hours', 120)->default('');
            $t->longText('body');
            $t->string('address', 250)->default('');
            $t->string('phone', 40)->default('');
            $t->string('whatsapp', 20)->default('');
            $t->string('map_url', 200)->default('');
            $t->decimal('latitude', 9, 6)->nullable();
            $t->decimal('longitude', 9, 6)->nullable();
            $t->boolean('active')->default(true);
            $t->bigInteger('sort_order')->default('0');
        });
        Schema::create('cars_carbrand', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->string('name', 100)->unique();
            $t->string('slug', 50)->unique();
        });
        Schema::create('cars_carcategory', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->string('seo_title', 250)->default('');
            $t->longText('seo_description');
            $t->string('seo_h1', 250)->default('');
            $t->string('canonical_url', 200)->default('');
            $t->string('robots', 40)->default('index,follow');
            $t->string('og_title', 250)->default('');
            $t->longText('og_description');
            $t->string('og_image', 200)->default('');
            $t->json('legacy_meta');
            $t->dateTime('created_at', 6);
            $t->dateTime('updated_at', 6);
            $t->string('name', 100);
            $t->string('slug', 50)->unique();
            $t->longText('description');
            $t->boolean('active')->default(true);
            $t->bigInteger('sort_order')->default('0');
        });
        Schema::create('cars_carfeature', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->string('name', 100)->unique();
        });
        Schema::create('cars_car_cities', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->unsignedBigInteger('car_id');
            $t->unsignedBigInteger('city_id');
        });
        Schema::create('cars_car_features', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->unsignedBigInteger('car_id');
            $t->unsignedBigInteger('carfeature_id');
        });
        Schema::create('cars_car', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->string('seo_title', 250)->default('');
            $t->longText('seo_description');
            $t->string('seo_h1', 250)->default('');
            $t->string('canonical_url', 200)->default('');
            $t->string('robots', 40)->default('index,follow');
            $t->string('og_title', 250)->default('');
            $t->longText('og_description');
            $t->string('og_image', 200)->default('');
            $t->json('legacy_meta');
            $t->dateTime('created_at', 6);
            $t->dateTime('updated_at', 6);
            $t->string('name', 200);
            $t->string('slug', 200)->unique();
            $t->string('legacy_path', 250)->unique()->default('');
            $t->string('legacy_id', 250)->unique()->default('');
            $t->unsignedBigInteger('brand_id');
            $t->string('model_name', 200)->default('');
            $t->unsignedBigInteger('category_id');
            $t->decimal('base_price', 12, 0);
            $t->bigInteger('year')->nullable();
            $t->string('engine', 100)->default('');
            $t->string('transmission', 20)->default('');
            $t->string('drive', 20)->default('');
            $t->bigInteger('seats')->nullable();
            $t->string('color', 100)->default('');
            $t->string('fuel', 100)->default('');
            $t->bigInteger('doors')->nullable();
            $t->decimal('deposit', 12, 0)->nullable();
            $t->bigInteger('mileage_limit')->nullable();
            $t->longText('description');
            $t->boolean('active')->default(true);
            $t->boolean('featured')->default(false);
            $t->boolean('accepts_requests')->default(true);
            $t->bigInteger('sort_order')->default('0');
        });
        Schema::create('cars_carimage', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->unsignedBigInteger('car_id');
            $t->string('original', 100);
            $t->string('image', 100)->default('');
            $t->string('small', 100)->default('');
            $t->string('card_image', 100)->default('');
            $t->string('card_small', 100)->default('');
            $t->bigInteger('card_width')->default('960');
            $t->bigInteger('card_height')->default('619');
            $t->string('legacy_url', 600)->default('');
            $t->string('alt', 250)->default('');
            $t->string('caption', 250)->default('');
            $t->boolean('is_main')->default(false);
            $t->bigInteger('sort_order')->default('0');
            $t->bigInteger('width')->default('1200');
            $t->bigInteger('height')->default('800');
            $t->json('variants');
        });
        Schema::create('cars_carprice', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->unsignedBigInteger('car_id');
            $t->bigInteger('min_days')->default('1');
            $t->bigInteger('max_days')->nullable();
            $t->decimal('daily_price', 12, 0);
            $t->string('label', 100)->default('');
            $t->decimal('deposit', 12, 0)->nullable();
            $t->bigInteger('mileage_limit')->nullable();
        });
        Schema::create('cars_cardiscount', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->unsignedBigInteger('car_id');
            $t->string('label', 100);
            $t->bigInteger('min_days');
            $t->bigInteger('max_days')->nullable();
            $t->bigInteger('percent');
        });
        Schema::create('cars_carspecification', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->unsignedBigInteger('car_id');
            $t->string('name', 100);
            $t->string('value', 250);
            $t->bigInteger('sort_order')->default('0');
        });
        Schema::create('pages_page', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->string('seo_title', 250)->default('');
            $t->longText('seo_description');
            $t->string('seo_h1', 250)->default('');
            $t->string('canonical_url', 200)->default('');
            $t->string('robots', 40)->default('index,follow');
            $t->string('og_title', 250)->default('');
            $t->longText('og_description');
            $t->string('og_image', 200)->default('');
            $t->json('legacy_meta');
            $t->dateTime('created_at', 6);
            $t->dateTime('updated_at', 6);
            $t->string('title', 200);
            $t->string('slug', 200)->unique();
            $t->string('path', 250)->unique();
            $t->longText('intro');
            $t->longText('body');
            $t->boolean('active')->default(true);
            $t->boolean('show_in_footer')->default(false);
            $t->boolean('legal_approved')->default(false);
        });
        Schema::create('pages_faq', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->string('question', 250);
            $t->longText('answer');
            $t->unsignedBigInteger('city_id')->nullable();
            $t->unsignedBigInteger('page_id')->nullable();
            $t->unsignedBigInteger('car_id')->nullable();
            $t->boolean('active')->default(true);
            $t->bigInteger('sort_order')->default('0');
        });
        Schema::create('seo_translation', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->unsignedBigInteger('content_type_id');
            $t->bigInteger('object_id');
            $t->string('language', 2);
            $t->boolean('published')->default(false);
            $t->string('name', 250)->default('');
            $t->string('title', 250)->default('');
            $t->longText('description');
            $t->string('h1', 250)->default('');
            $t->longText('content');
            $t->longText('intro');
            $t->string('address', 250)->default('');
            $t->string('hours', 120)->default('');
            $t->string('fuel', 100)->default('');
            $t->string('color', 100)->default('');
            $t->string('caption', 250)->default('');
            $t->longText('whatsapp_message');
            $t->string('og_title', 250)->default('');
            $t->longText('og_description');
            $t->string('hero_title', 250)->default('');
            $t->longText('hero_text');
            $t->string('hero_price_caption', 150)->default('');
            $t->string('hero_steps_caption', 250)->default('');
            $t->string('partner_title', 250)->default('');
            $t->longText('partner_description');
            $t->longText('partner_whatsapp_message');
            $t->string('footer_text', 250)->default('');
            $t->dateTime('updated_at', 6);
        });
        Schema::create('seo_redirect', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->string('old_path', 500)->unique();
            $t->string('new_path', 500);
            $t->bigInteger('status_code')->default('301');
            $t->boolean('active')->default(true);
        });
        Schema::create('bookings_bookingrequest', function (Blueprint $t) {
            $t->bigIncrements('id');
            $t->string('name', 120);
            $t->string('phone', 30);
            $t->unsignedBigInteger('city_id');
            $t->longText('comment');
            $t->boolean('consent')->default(false);
            $t->longText('consent_text');
            $t->longText('manager_note');
            $t->string('source_page', 600)->default('');
            $t->string('landing_page', 600)->default('');
            $t->string('referrer', 600)->default('');
            $t->string('utm_source', 200)->default('');
            $t->string('utm_medium', 200)->default('');
            $t->string('utm_campaign', 200)->default('');
            $t->string('utm_content', 200)->default('');
            $t->string('utm_term', 200)->default('');
            $t->dateTime('created_at', 6);
            $t->dateTime('updated_at', 6);
            $t->unsignedBigInteger('car_id')->nullable();
            $t->date('start_date')->nullable();
            $t->date('end_date')->nullable();
            $t->string('status', 20)->default('NEW');
            $t->string('kind', 20)->default('booking');
        });
        Schema::table('django_admin_log', fn (Blueprint $t) => $t->foreign('user_id')->references('id')->on('auth_user')->cascadeOnDelete());
        Schema::table('django_admin_log', fn (Blueprint $t) => $t->foreign('content_type_id')->references('id')->on('django_content_type')->nullOnDelete());
        Schema::table('auth_permission', fn (Blueprint $t) => $t->foreign('content_type_id')->references('id')->on('django_content_type')->cascadeOnDelete());
        Schema::table('auth_group_permissions', fn (Blueprint $t) => $t->foreign('group_id')->references('id')->on('auth_group')->cascadeOnDelete());
        Schema::table('auth_group_permissions', fn (Blueprint $t) => $t->foreign('permission_id')->references('id')->on('auth_permission')->cascadeOnDelete());
        Schema::table('auth_user_groups', fn (Blueprint $t) => $t->foreign('user_id')->references('id')->on('auth_user')->cascadeOnDelete());
        Schema::table('auth_user_groups', fn (Blueprint $t) => $t->foreign('group_id')->references('id')->on('auth_group')->cascadeOnDelete());
        Schema::table('auth_user_user_permissions', fn (Blueprint $t) => $t->foreign('user_id')->references('id')->on('auth_user')->cascadeOnDelete());
        Schema::table('auth_user_user_permissions', fn (Blueprint $t) => $t->foreign('permission_id')->references('id')->on('auth_permission')->cascadeOnDelete());
        Schema::table('core_sitesettings', fn (Blueprint $t) => $t->foreign('hero_car_id')->references('id')->on('cars_car')->nullOnDelete());
        Schema::table('cars_car_cities', fn (Blueprint $t) => $t->foreign('car_id')->references('id')->on('cars_car')->cascadeOnDelete());
        Schema::table('cars_car_cities', fn (Blueprint $t) => $t->foreign('city_id')->references('id')->on('locations_city')->cascadeOnDelete());
        Schema::table('cars_car_features', fn (Blueprint $t) => $t->foreign('car_id')->references('id')->on('cars_car')->cascadeOnDelete());
        Schema::table('cars_car_features', fn (Blueprint $t) => $t->foreign('carfeature_id')->references('id')->on('cars_carfeature')->cascadeOnDelete());
        Schema::table('cars_car', fn (Blueprint $t) => $t->foreign('brand_id')->references('id')->on('cars_carbrand')->restrictOnDelete());
        Schema::table('cars_car', fn (Blueprint $t) => $t->foreign('category_id')->references('id')->on('cars_carcategory')->restrictOnDelete());
        Schema::table('cars_carimage', fn (Blueprint $t) => $t->foreign('car_id')->references('id')->on('cars_car')->cascadeOnDelete());
        Schema::table('cars_carprice', fn (Blueprint $t) => $t->foreign('car_id')->references('id')->on('cars_car')->cascadeOnDelete());
        Schema::table('cars_cardiscount', fn (Blueprint $t) => $t->foreign('car_id')->references('id')->on('cars_car')->cascadeOnDelete());
        Schema::table('cars_carspecification', fn (Blueprint $t) => $t->foreign('car_id')->references('id')->on('cars_car')->cascadeOnDelete());
        Schema::table('pages_faq', fn (Blueprint $t) => $t->foreign('city_id')->references('id')->on('locations_city')->nullOnDelete());
        Schema::table('pages_faq', fn (Blueprint $t) => $t->foreign('page_id')->references('id')->on('pages_page')->nullOnDelete());
        Schema::table('pages_faq', fn (Blueprint $t) => $t->foreign('car_id')->references('id')->on('cars_car')->nullOnDelete());
        Schema::table('seo_translation', fn (Blueprint $t) => $t->foreign('content_type_id')->references('id')->on('django_content_type')->cascadeOnDelete());
        Schema::table('bookings_bookingrequest', fn (Blueprint $t) => $t->foreign('city_id')->references('id')->on('locations_city')->restrictOnDelete());
        Schema::table('bookings_bookingrequest', fn (Blueprint $t) => $t->foreign('car_id')->references('id')->on('cars_car')->restrictOnDelete());
        Schema::table('seo_translation', fn (Blueprint $t) => $t->unique(['content_type_id', 'object_id', 'language'], 'unique_object_translation'));
        Schema::table('cars_car_cities', fn (Blueprint $t) => $t->unique(['car_id', 'city_id']));
        Schema::table('cars_car_features', fn (Blueprint $t) => $t->unique(['car_id', 'carfeature_id']));
    }

    public function down(): void
    {
        Schema::disableForeignKeyConstraints();
        Schema::dropIfExists('bookings_bookingrequest');
        Schema::dropIfExists('seo_redirect');
        Schema::dropIfExists('seo_translation');
        Schema::dropIfExists('pages_faq');
        Schema::dropIfExists('pages_page');
        Schema::dropIfExists('cars_carspecification');
        Schema::dropIfExists('cars_cardiscount');
        Schema::dropIfExists('cars_carprice');
        Schema::dropIfExists('cars_carimage');
        Schema::dropIfExists('cars_car');
        Schema::dropIfExists('cars_car_features');
        Schema::dropIfExists('cars_car_cities');
        Schema::dropIfExists('cars_carfeature');
        Schema::dropIfExists('cars_carcategory');
        Schema::dropIfExists('cars_carbrand');
        Schema::dropIfExists('locations_city');
        Schema::dropIfExists('core_menulink');
        Schema::dropIfExists('core_sitesection');
        Schema::dropIfExists('core_interfacetext');
        Schema::dropIfExists('core_contentblock');
        Schema::dropIfExists('core_sitesettings');
        Schema::dropIfExists('django_content_type');
        Schema::dropIfExists('auth_user');
        Schema::dropIfExists('auth_user_user_permissions');
        Schema::dropIfExists('auth_user_groups');
        Schema::dropIfExists('auth_group');
        Schema::dropIfExists('auth_group_permissions');
        Schema::dropIfExists('auth_permission');
        Schema::dropIfExists('django_admin_log');
        Schema::enableForeignKeyConstraints();
    }
};
